services:
  aprovar-app:
    build: .
    container_name: aprovar-app
    hostname: aprovar-app
    restart: always
    env_file:
      - .env-app
    depends_on:
      - aprovar-db
    networks:
      - aprovar

  aprovar-db:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.29
    container_name: aprovar-db
    hostname: aprovar-db
    restart: unless-stopped
    env_file:
      - .env-db
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - aprovar-db:/usr/share/elasticsearch/data
      # Production
      # - /opt/aprovar/certificados:/usr/share/elasticsearch/config/certs:ro
      # Development
      - ./certs:/usr/share/elasticsearch/config/certs:ro
    networks:
      - aprovar

  proxy:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    hostname: "proxy"
    container_name: "proxy"
    restart: always
    environment:
      TZ: America/Sao_Paulo

    networks:
      - aprovar
    ports:
    - 80:80
    - 443:443

    volumes:
    - type: bind
      source: /opt/aprovar/certificados
      target: /etc/nginx/certificados

    - type: bind
      source: /opt/aprovar/nginx
      target: /etc/nginx/conf.d

volumes:
  aprovar-db:
    name: aprovar-db

networks:
  aprovar:
    name: aprovar
    driver: bridge
